### ISSUE TITLE
Goblirangs' bees target flying enemies but do not damage them

### ISSUE THREAD

**Issue by skankle** [cigumo/krvi#181] opened 2020-10-02 14:20 UTC
The Angry Bees ability targets an individual enemy and follows them, dealing damage in an aoe until they expire or the target dies, after which they remain in the same place until they expire. As it stands they can target and follow flying enemies but will not deal damage to them.

![image](https://user-images.githubusercontent.com/72265033/94934403-94696100-04c3-11eb-8cfd-0938e20ec770.png)

**Comment by sunnydaler** [comment] 2020-10-02 23:23
Duplicate of #169

**Closed by sunnydaler** 2020-10-02 23:23 UTC
Labels: z.duplicate
