### ISSUE TITLE
Suggestion: Add the Ancient Ghosts kill achievement

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#330] opened 2022-02-21 21:45 UTC
This is an issue on the mobile versions as well, but the Ancient Ghosts lack an achievement for completing their level. This is despite the fact that it has a name and maybe art, though I'm uncertain on this. 

It isn't a priority by any means but it's odd that it's missing.

**Comment by Mmlh1** [comment] 2022-02-24 13:20
See #282

**Comment by cigumo** [comment] 2022-02-28 11:43
duplicate of #282

**Closed as completed by cigumo** 2022-02-28 11:43 UTC
