### ISSUE TITLE
Bolgur Boss Fight spawn issue

### ISSUE THREAD

**Issue by AerisDraco** [cigumo/krvi#43] opened 2020-09-03 10:01 UTC
Most units spawned during the fight spawn from weird places.
West entrance enemies spawn a bit in front of the entrance, walk backwards, and then join the normal path.
East entrance enemies spawn north of the east exit and then join the normal path.

**Comment by cigumo** [comment] 2020-09-03 16:35
duplicate of #32

**Closed by cigumo** 2020-09-03 16:35 UTC
Labels: 1.PRIO.HIGH
