### ISSUE TITLE
I cant upgrade the pre-placed balloon towers (stage 6 iron) / Mmlh

### ISSUE THREAD

**Issue by cigumo** [cigumo/krvi#191] opened 2020-10-05 13:40 UTC
![](https://cdn.discordapp.com/attachments/493772773081219073/761341999294840833/Kingdom_Rush_Vengeance_01_10_2020_23_38_48.png)

**Comment by sunnydaler** [comment] 2020-10-05 14:43
Duplicate of #180

**Closed by sunnydaler** 2020-10-05 14:43 UTC
Labels: w.gameplay, z.duplicate
