### ISSUE TITLE
next wave icon appears and tower menu gets closed

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krvi#173] opened 2020-09-29 01:44 UTC
![1](https://user-images.githubusercontent.com/43391939/94503120-b2735f00-0240-11eb-97b3-46e595888178.gif)
![2](https://user-images.githubusercontent.com/43391939/94503121-b30bf580-0240-11eb-9ebe-f74720b6df80.gif)

**Comment by cigumo** [comment] 2020-09-29 02:13
can't reproduce it

**Comment by sunnydaler** [comment] 2020-10-09 12:34
Top: click a holder and open tower menu. move the mouse pointer away from a tower icon (it should stay inside the menu ui thou) just when the wave icon appears. 
Bottom: click a holder and open menu. Move away cursor after the wave icon appears

**Comment by cigumo** [comment] 2020-10-09 13:12
https://cdn.discordapp.com/attachments/493772773081219073/764101475461758986/KRV_failed_upgrade.mp4

**Comment by sunnydaler** [comment] 2020-10-12 13:07
https://steamcommunity.com/app/1367550/discussions/0/2968393780775727055/

**Comment by cigumo** [comment] 2020-10-12 13:27
It happens when: 
- quick menu: the mouse is in movement over a quick menu icon and the wave flag appears
- power: the mouse is moved when the wave flag appears

**Comment by cigumo** [comment] 2020-10-12 15:07
fixed in 1.9.9.16

**Closed by cigumo** 2020-10-12 15:07 UTC
Labels: 1.PRIO.HIGH, t.desktop, w.ui, z.extra
