### ISSUE TITLE
[Suggestion] Make the wave icon transparent when spell is selected

### ISSUE THREAD

**Issue by Emicon97** [cigumo/krvi#342] opened 2022-03-08 20:27 UTC
In all the other Kingdom Rush games, when you have selected a spell, you can move your mouse above the next wave icon and even click there to use the spell (or move your hero) without having to call the new wave. But this is impossible on Vengeance because the wave icon will be prioritized and unselect the spell.

**Comment by Mmlh1** [comment] 2022-04-26 22:06
Duplicate of #302

**Closed as completed by Mmlh1** 2022-04-26 22:06 UTC
Labels: z.duplicate
